In [1]:
import torch
print(torch.__version__)


2.9.0+cpu


In [2]:

a = torch.tensor([1, 2, 3])
print("Tensor a:", a)


b = torch.tensor([[1, 2], [3, 4]])
print("Tensor b:\n", b)


zeros = torch.zeros(3, 3)
ones = torch.ones(2, 2)
random = torch.rand(2, 3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Random:\n", random)


Tensor a: tensor([1, 2, 3])
Tensor b:
 tensor([[1, 2],
        [3, 4]])
Zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Ones:
 tensor([[1., 1.],
        [1., 1.]])
Random:
 tensor([[0.0164, 0.5473, 0.6346],
        [0.6271, 0.2509, 0.6248]])


In [3]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)
y = torch.tensor([1, 2, 3], dtype=torch.int64)

print("x dtype:", x.dtype)
print("y dtype:", y.dtype)


x dtype: torch.float32
y dtype: torch.int64


In [4]:
a = torch.tensor([10, 20, 30])
b = torch.tensor([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: tensor([11, 22, 33])
Subtraction: tensor([ 9, 18, 27])
Multiplication: tensor([10, 40, 90])
Division: tensor([10., 10., 10.])


In [5]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

vector = torch.tensor([10, 20, 30])

result = matrix + vector
print(result)


tensor([[11, 22, 33],
        [14, 25, 36]])


In [6]:
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("First row:", t[0])
print("Second column:", t[:, 1])
print("Element (1,2):", t[1, 2])


First row: tensor([1, 2, 3])
Second column: tensor([2, 5])
Element (1,2): tensor(6)


In [7]:
x = torch.arange(12)

print("Original:", x)
print("Reshaped (3x4):\n", x.reshape(3, 4))
print("Reshaped (2x6):\n", x.view(2, 6))


Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Reshaped (3x4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Reshaped (2x6):
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [8]:
x = torch.tensor(2.0, requires_grad=True)

y = x ** 3 + 2 * x
y.backward()

print("y =", y.item())
print("dy/dx =", x.grad)


y = 12.0
dy/dx = tensor(14.)


# Section 2

In [10]:
import tensorflow as tf
print(tf.__version__)


2.19.0


In [11]:
# Define matrices
A = tf.constant([[1, 2],
                 [3, 4]], dtype=tf.float32)

B = tf.constant([[5, 6],
                 [7, 8]], dtype=tf.float32)

print("Matrix A:\n", A)
print("Matrix B:\n", B)


Matrix A:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Matrix B:
 tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [12]:
add = tf.add(A, B)
sub = tf.subtract(A, B)

print("A + B:\n", add)
print("A - B:\n", sub)


A + B:
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
A - B:
 tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)


In [13]:
mul = tf.matmul(A, B)
print("Matrix Multiplication (A x B):\n", mul)


Matrix Multiplication (A x B):
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [14]:
elementwise = tf.multiply(A, B)
print("Element-wise Multiplication:\n", elementwise)


Element-wise Multiplication:
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)


In [15]:
transpose_A = tf.transpose(A)
print("Transpose of A:\n", transpose_A)


Transpose of A:
 tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)


In [16]:
det_A = tf.linalg.det(A)
print("Determinant of A:", det_A.numpy())


Determinant of A: -2.0


In [17]:
inverse_A = tf.linalg.inv(A)
print("Inverse of A:\n", inverse_A)


Inverse of A:
 tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)


In [18]:
v = tf.constant([3.0, 4.0])
norm = tf.norm(v)

print("Vector:", v.numpy())
print("L2 Norm:", norm.numpy())


Vector: [3. 4.]
L2 Norm: 5.0


# Section 3

In [19]:
import numpy as np
class Perceptron:
    def __init__(self, learning_rate=0.1, epochs=10):
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self, X, y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0

        for _ in range(self.epochs):
            for i in range(len(X)):
                y_pred = self.predict(X[i])
                error = y[i] - y_pred
                self.weights += self.lr * error * X[i]
                self.bias += self.lr * error

    def predict(self, x):
        linear_output = np.dot(x, self.weights) + self.bias
        return 1 if linear_output >= 0 else 0


In [20]:
# AND gate data
X_and = np.array([[0,0], [0,1], [1,0], [1,1]])
y_and = np.array([0, 0, 0, 1])

# Train perceptron
and_perceptron = Perceptron()
and_perceptron.fit(X_and, y_and)

# Test AND gate
print("AND Gate Results:")
for x in X_and:
    print(f"{x} -> {and_perceptron.predict(x)}")


AND Gate Results:
[0 0] -> 0
[0 1] -> 0
[1 0] -> 0
[1 1] -> 1


In [21]:
# OR gate data
X_or = np.array([[0,0], [0,1], [1,0], [1,1]])
y_or = np.array([0, 1, 1, 1])

# Train perceptron
or_perceptron = Perceptron()
or_perceptron.fit(X_or, y_or)

# Test OR gate
print("\nOR Gate Results:")
for x in X_or:
    print(f"{x} -> {or_perceptron.predict(x)}")



OR Gate Results:
[0 0] -> 0
[0 1] -> 1
[1 0] -> 1
[1 1] -> 1


# Section 4

In [22]:
import torch
import torch.nn as nn
import torch.optim as optim


In [23]:
# XOR input and output
X = torch.tensor([[0., 0.],
                  [0., 1.],
                  [1., 0.],
                  [1., 1.]])

y = torch.tensor([[0.],
                  [1.],
                  [1.],
                  [0.]])


In [24]:
class XORNet(nn.Module):
    def __init__(self):
        super(XORNet, self).__init__()
        self.hidden = nn.Linear(2, 4)
        self.output = nn.Linear(4, 1)

    def forward(self, x):
        x = torch.relu(self.hidden(x))
        x = torch.sigmoid(self.output(x))
        return x


In [25]:
model = XORNet()

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)


In [26]:
epochs = 5000

for epoch in range(epochs):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")


Epoch 0, Loss: 0.6762
Epoch 1000, Loss: 0.0008
Epoch 2000, Loss: 0.0002
Epoch 3000, Loss: 0.0001
Epoch 4000, Loss: 0.0000


In [29]:
with torch.no_grad():
    predictions = model(X)
    predictions = (predictions > 0.5).float()

print("\nXOR Predictions:")
for i in range(len(X)):
    print(f"{X[i].tolist()} -> {predictions[i].item()}")



XOR Predictions:
[0.0, 0.0] -> 0.0
[0.0, 1.0] -> 1.0
[1.0, 0.0] -> 1.0
[1.0, 1.0] -> 0.0


# Section 5

In [39]:
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt


In [40]:
# Set seed for reproducibility
torch.manual_seed(42)

# Generate input data
X = torch.rand(100, 2)

# Regression target
y = 3 * X[:, 0:1] + 2 * X[:, 1:2]


In [41]:
class SimpleRegressionNN(nn.Module):
    def __init__(self):
        super(SimpleRegressionNN, self).__init__()

        # Input → Hidden (2 neurons)
        self.hidden = nn.Linear(2, 2)

        # Hidden → Output (1 neuron)
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        h = torch.relu(self.hidden(x))  # f(z¹)
        out = self.output(h)            # Linear output f(z²)
        return out


In [42]:
model = SimpleRegressionNN()

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)


In [43]:
epochs = 1000
losses = []

for epoch in range(epochs):
    optimizer.zero_grad()

    predictions = model(X)
    loss = criterion(predictions, y)

    loss.backward()
    optimizer.step()

    losses.append(loss.item())

    if epoch % 200 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.6f}")


Epoch 0, Loss: 8.915829
Epoch 200, Loss: 2.188420
Epoch 400, Loss: 1.092106
Epoch 600, Loss: 1.016308
Epoch 800, Loss: 1.014443


In [44]:
with torch.no_grad():
    test_sample = torch.tensor([[0.5, 0.2]])
    pred = model(test_sample)

print("Predicted Output:", pred.item())
print("Expected Output:", 3*0.5 + 2*0.2)


Predicted Output: 2.502650022506714
Expected Output: 1.9
